### PR TITLE
Implemented FlatList with Example for Large data array

### PR DESCRIPTION
**Pull request by mehimanshupatil**
WRT #94 Issue, have implemented flatList and also have added an example

Note 
>  Not tested on ios device
> For flat list key should be a string but that can be overcome by passing `keyExtractor` which will return string

### CODE REVIEW

**Comment by peacechen** [comment]
Thanks @mehimanshupatil 👍 
I like that you kept the ScrollView rendering method intact for existing users. Is this ready for merge or is more testing needed?

**Comment by mehimanshupatil** [comment]
Thanks @peacechen 
Let wait for this weekend. Since we are implementing flatList I will try to fix #93. Also, can you test this on an iOS device?

**Comment by mehimanshupatil** [comment]
@peacechen you can merge it. But I have not tested on iOS

**Comment by kg-currenxie** [comment]
Would love this to get merged. I'm also making a country selector :)

**Comment by peacechen** [comment]
@kg-currenxie 

Thanks for the reminder, and apologies for the delay. Please test this before I publish.  You can use this in your package.json to pull directly from the repo:
```
dependencies: {
  "react-native-modal-selector": "https://github.com/peacechen/react-native-modal-selector.git",
}
```

**Comment by kg-currenxie** [comment]
Wow, thanks for doing this so fast!

Found a small bug

```
    renderFlatlistOption = ({ item, index, separators }) => {
        if (item.section) {
            return this.renderSection(item);
        }
        const numItems = this.props.data.length;
        this.renderOption(item, index === (numItems - 1), index === 0); <------- missing return
    }
```

My flatlist showed an empty list :) i debugged and after adding `return`, it works, and the modal opens instantly, and the initial options (images) load much faster!

**Comment by kg-currenxie** [comment]
Oh, and also, a small TS type error, but I can't figure out where it comes from:

Screenshot 2021-04-06 at 13 28 25

**Comment by mehimanshupatil** [comment]
ok, @kg-currenxie thank for testing. You can submit a PR for the same or else I will submit a PR in coming weekend.

**Comment by peacechen** [comment]
Thanks @kg-currenxie for noting those bugs. I pushed a commit to fix the return in `renderFlatlistOption()`.

@mehimanshupatil Can you confirm that the TS definition fix that kg proposed fixes the other problem?

**Comment by peacechen** [comment]
Fix published in 2.0.4

**Pull request merged**
