### PR TITLE
reverted style changes introduced in orientation fixes

### PR DESCRIPTION
**Pull request by ChangedLater**
The fixes to support both orientations made the modal look quite different. These changes keep the modal styled the same as before the orientation changes but also allows the modal to size correctly in both orientations.

### CODE REVIEW

**Comment by mikaello** [comment]
Which phones have you tested on? Does not look so good on the phones I have tested:

On Android (Samsung S7):
modal

On iPhone S6:
modal_ios

**Comment by peacechen** [comment]
RN overhauled the layout engine a few versions ago (0.40?).  Maybe that's the difference.

**Comment by ChangedLater** [comment]
@mikaello I didn't test enough obviously. I only used a small option list on smaller devices.

I have more thorough look into it either today or tomorrow.

**Comment by mikaello** [comment]
But I see your concern, the modal looks quite different when there are few items in the list, so a fix for this that also supports horizontal view and looks good with many items would have been great.

changed_style

**Comment by ChangedLater** [comment]
@mikaello Yeah thats the exact hing that was bothering me. Hopefully this week/weekend ill be able to spend some time on it (very busy atm).

**Comment by mikaello** [comment]
I tried this

```javascript
optionContainer {
  flexShrink: 1, // flexWrap: 'wrap' also works
  ...
)

cancelContainer {
  flexGrow: 1,
  ...
}
```

And that seem to work both on Android and iOS, with both many and few items, in both landscape and portrait. But it would have been nice to test this on more devices. I have only tested in iOS simulator and physical device Samsung S7.

**Comment by peacechen** [comment]
The iOS simulator is true to the layout engine.  Testing iPad 9.7" and 12.9", along with and iPhone 5-7, should validate the behavior on a wide variety of iOS resolutions.

Android emulator hopefully is as reliable for layout.  It supports lots of resolution screens AFAIK.

**Comment by ChangedLater** [comment]
I've updated the pull request and tested on an iPad pro 10.5 and and iPhone 6S (physical devices), i also tested on the iPhone 7 Plus simulator and the iPhone 5 simulator. It all now works as expected on these models for both large and small modals. Unfortunately i don't have android studio set up atm to test with.

**Comment by peacechen** [comment]
It works well in the iOS simulator.  The value for `overlayStyle: { padding: '10%' }` creates a rather large border on iPhone 7.  How about defaulting it to 5%?   While users can override it with the overlayStyle prop, it helps to set defaults that look good out of the box.

Another potential issue is that percentage padding was added in RN 0.42, so default padding will be wrong for RN 0.41 and earlier.  Should we try to address that in code or document this and have users override it for older versions of RN?

**Comment by mikaello** [comment]
I have tested on a few more (older) Android-devices now, and all seem to work fine. But I agree with you @peacechen, `padding: '10%'` seems to be a little to much, for Android this is especially in landscape view that the padding on top and bottom seems a bit exaggerated.

**Comment by ChangedLater** [comment]
@peacechen @mikaello Reducing the padding makes it look much nicer on smaller devices. Ive updated this PR with a reduction of the padding to 5%. I has a look on 10.5 ipad pro, iPhone 6s (both physical) and iphone 7plus and 5 simulators.

**Comment by peacechen** [comment]
This looks good.  Would you mind updating overlayStyle prop in the Readme?  I can't push to your fork to add it to this PR.
```
`overlayStyle`      | object   | Yes      | { flex: 1, padding: '5%', justifyContent: 'center', backgroundColor: 'rgba(0,0,0,0.7)' } | style definitions for the overlay background element. RN <= 0.41 should override this with pixel value for padding.
```

**Comment by ChangedLater** [comment]
@peacechen Ive updated the pull request with the readme changes. @mikaello @peacechen Thanks guys, its great to see this package active.

**Comment by mikaello** [comment]
Well done, and thanks for your contribution! I merged it now, and up-ed the version to 0.0.19 in NPM.

**Comment by peacechen** [comment]
Appreciate your help @ChangedLater @mikaello 👍

**Pull request merged**
