### PR TITLE
Eslint rules

### PR DESCRIPTION
**Pull request by fabriziomoscon**
Fixes issue #13 

- The first commit simply applies rules that enforce the code style and formatting already used
- the second commit could be discussed/amended/improved and it is based on my personal preference for readability

### CODE REVIEW

**Comment by peacechen** [comment]
Thanks @fabriziomoscon

**Comment by mikaello** [comment]
I see that you are adding `react` and `react-native` as devDependencies in package.json, this adds 89 MB to node_modules (from 40 MB to 129 MB), and I guess this is to get read of the import errors caused by importing from `react` and `react-native`. In addition to space, it also adds unused dependencies that are there just to get read of linter-errors.

The warnings could be removed by deactivating the `import/no-unresolved` rule, or maybe adding an exception for `react` and `react-native`?

**Comment by mikaello** [comment]
You are also adding constraints on code formatting in eslint, and adding formatting not specified in .eslintrc (such as how you structure object-properties). Would it be better to have a dedicated tool for this, such as prettier? The linter-file from [react-native-vector-icons ](https://github.com/oblador/react-native-vector-icons/blob/master/.eslintrc) have this implemented. Then you are sure that everyone are following the same coding conventions, and you don't have analyse the file to be sure your doing it right.

**Comment by peacechen** [comment]
Good catch @mikaello .  How are exceptions added for the react [native] imports?   devDependencies are ignored when this package is consumed by others.  What case makes them bloat node_modules unnecessarily?

I've contributed to other projects which use prettier and it works well.  I don't have a strong opinion between prettier and eslint, but I agree that prettier would do a better job at enforcing formatting.

**Comment by mikaello** [comment]
In .eslintrc you could ignore `react` and `react-native` with this rule: `import/no-unresolved: [2, { ignore: ['react', 'react-native'] }],`.

Nowadays I guess 89 MB is not very much, but it feels unnecessary, especially just to get rid of a linter-error. And when I inspect a package.json in a new project and I look at the devpendencies, I assume that what is required is used, but from I can see, that is not the case here.

**Comment by peacechen** [comment]
@fabriziomoscon or @mikaello -- Would you mind creating another commit with the additional `import/no-unresolved` eslint rule and remove react/react-native from devDependencies?  I imagine package-json.lock will also need to be updated. Which tool was used to create that?

**Comment by mikaello** [comment]
Done. I think since version 5 was released of NPM, `npm install` generates a package-lock.json (similar way yarn creates yarn.lock when invoked).

**Comment by fabriziomoscon** [comment]
Thank you for the comments.
I appreciate the concerns about size, but please note that dev dependencies are ONLY installed when developing the library, so they don't affect users, plus they are necessary when adding flow for static typing checks.
They are necessary to make sure you are importing something present in react and react-native, ignoring is equivalent to not using the tool.
In regards to formatting I have no intention of forcing any specific formatting. I didn't expect my changes to be merged without discussion.
In regards to prettier I don't have experience so please go on installing it as you see fit.

**Comment by mikaello** [comment]
For static typing checking with flow I realise that they could be useful to have there. But for flow to work we should enable it in index.js, update .flowconfig and add flow-bin as an devdependency.

**Comment by peacechen** [comment]
I will refrain from merging PR's to allow for more discussion.  I erred on the side of expediency and hope it hasn't caused too much confusion.

**Comment by mikaello** [comment]
No worries :-)

**Pull request merged**
