### PR TITLE
Accessibility Flexibility

### PR DESCRIPTION
**Pull request by jessamp**
added some flexibility for accessibility. Included two new props, one for scrollview modal and cancel button. There was also a small bug with android where the 2nd option was being focused instead of the 1st. That should be fixed as well.

### CODE REVIEW

**Comment by peacechen** [comment]
Thanks @jessamp .

It looks like the `accessible` prop was replaced by the new props, but it's still in the Readme as a separate prop.  Should it be removed from the documentation?

**Comment by jessamp** [comment]
Oh yes it should. I thought I removed it.

**Comment by jessamp** [comment]
Oh wait....no it shouldn't....that actually controls the individual items in the list. I left it there in case someone wants to do something different for the accessibility for individual items. But I'll rename it so it's not confusing.

Also, I'm adding another accessible term. I just came across another issue when I use this as a wrapper. We should add the capability to control that accessibility as well in case their wrapped component has accessibility specifically defined.

**Comment by jessamp** [comment]
@peacechen changes were added. Thanks!

**Comment by peacechen** [comment]
Thanks again @jessamp .   It took some head-scratching to understand what `wrappedComponentAccessible` applied to.  Hope you don't mind that I renamed it to `openButtonContainerAccessible`

**Comment by jessamp** [comment]
Sounds good to me!

**Comment by jessamp** [comment]
@peacechen curious when you'll be able to push the change out to the npm release?

**Comment by peacechen** [comment]
We'll publish soon.  It'll be bumped to 1.0.0 since the updated accessibility props are breaking changes.

**Comment by mikaello** [comment]
It is published now as v1.0.0. Could then issue #88 be marked as resolved?

**Pull request merged**
