### PR TITLE
childrenContainerStyle and touchableStyle props added

### PR DESCRIPTION
**Pull request by eduardojunio**

### CODE REVIEW

**Comment by peacechen** [comment]
Thanks for the PR @eduardojunio 

The name `containerStyle` may be misleading, as their is an overall container style prop named `style`.  That naming is unfortunate since it's ambiguous, but changing it would affect current users.
How about renaming `containerStyle` to `childrenContainerStyle` ?

**Comment by eduardojunio** [comment]
@peacechen yeah, I only put the `containerStyle` name because I didn't had other name in mind, but I agree with you. I'll update the PR and tag you.

**Comment by eduardojunio** [comment]
@peacechen PR updated. Thank you for keeping this lib updated! 😄

**Comment by peacechen** [comment]
Looks good. Thanks @eduardojunio

**Pull request merged**
