### PR TITLE
Add selectedKey prop

### PR DESCRIPTION
**Pull request by JoseVf**
The value provided must be a key present in one item of the array items provided as data.
If the key provided is not present in the array, displayed value will be `initValue`.

E.g: If I have this array as data
```
let data = [
  {label: 'First option', key: 0},
  {label: 'Second option', key: 1},
  {label: 'Third option', key: 2},
]
```
and I want the second one to be displayed (`Second option`), I have to pass `1` on `selectedKey`:
```
<ModalSelector
  data={data}
  selectedKey={1}
/>
```
closes: https://github.com/peacechen/react-native-modal-selector/issues/52, https://github.com/peacechen/react-native-modal-selector/issues/63, https://github.com/peacechen/react-native-modal-selector/issues/80

### CODE REVIEW

**Comment by JoseVf** [comment]
**Note:** I developed this according to my specific needs, if you know a way to make this better I'm open to suggestions!

**Comment by peacechen** [comment]
Thanks @JoseVf 

It would be more powerful and flexible if the prop were `selectedKey` to match the data passed to this component.  With an index, the user of the library must keep track of where the item is in the array that is to be pre-selected.  That order could change if something is inserted into the array.
With selectedKey, this library can look it up regardless of where it lives in the array.

**Comment by JoseVf** [comment]
@peacechen Sure! I'll work on that.

**Comment by peacechen** [comment]
Thanks again @JoseVf 

I'll make a small adjustment for readability.

**Comment by JoseVf** [comment]
@peacechen No problem, go ahead.

**Comment by peacechen** [comment]
I started a small change to selectedKey, only to realize that selectedLabel would be more human-readable.  However, after analyzing the code again, it appears that the `initValue` prop does allow for pre-selecting an item.  Would you mind testing `initValue` without using the `selectedLabel` prop?

**Comment by JoseVf** [comment]
The intended behavior (IMO) is to have a *valid* initially selected item (like a preloaded `key` and `label` frequently provided by the server), currently there is no way to have this.
I was analyzing the code and realised that I also have to change `changedItem` value to achieve this, but I don't think that changing `selectedKey` to `selectedLabel` is the best approach in this case. Also is better to have a `selectedKey` instead of `selectedLabel` because the `key`, in theory, must be unique, the label not.

**Comment by peacechen** [comment]
You're right, the key must be unique and is a better choice.  It would be silly to have multiple labels with the same value, but it is possible so not worth risking bugs there.
Yes please update `changedItem` as well.  Apologies for the churn.

Please also update the Readme with the new prop.

**Comment by JoseVf** [comment]
@peacechen Don't worry, your question also helped me to realise that I had a bug 😄

**Comment by peacechen** [comment]
This looks good.   Is there any concern if the user changes the `selectedKey` prop?  It's hard to predict how people will use it, but if they change the prop, they may expect the selected item to change as well.  That would be handled under `componentDidUpdate`

**Comment by JoseVf** [comment]
Maybe that would be better handled by a `setSelectedKey`/`setSelectedItem`  method?

**Comment by JoseVf** [comment]
Before:  
before

After:  
after

**Comment by peacechen** [comment]
Good stuff @JoseVf.  I'll review some more and merge soon.

**Comment by dhukarizwan** [comment]
@peacechen @JoseVf - This is much needed feature! Could this be published on npm?

**Comment by peacechen** [comment]
@dhukarizwan 
Version 1.0.3 has been published on npm.  I was hoping that this would get some more testing first, but the risk is relatively low.  Please report any bugs that you find with the new version.

**Comment by dhukarizwan** [comment]
@peacechen - Really appreciate your quick action on this.

**Comment by pierol** [comment]
Sorry, i want to set option programmatically, but if i set the props selectedKey (through a state variable) the component doesn't re-render and it doesn't change when i set a new value to the state variable. I would like viewing the code of @JoseVf  of the demo showed: when i click a button i change the selected value.

**Pull request merged**
