### PR TITLE
#44 Add TouchableOpacity activeOpacity option via props

### PR DESCRIPTION
**Pull request by jankarres**
Set the opacity of TouchableOpacity on touch via props.

See issue #44.

### CODE REVIEW

**Comment by peacechen** [comment]
Thanks @jankarres .  This looks good in general.  However there are 3 occurrences of `TouchableOpacity` and it would be good to add opacity props to all of them.  If the other 2 aren't that useful, rename the prop to be more descriptive of which TouchableOpacity it's applying to (e.g. touchableContainerActiveOpacity)

**Comment by jankarres** [comment]
Thanks for your feedback. You're right, I missed two `TouchableOpacity`. I think it makes sense to include the option there as well.

**Comment by peacechen** [comment]
Thanks @jankarres 

@M1chaelChen also requested this feature recently.  Is a single prop controlling all TouchableOpacity opacities good enough?  Or are you looking for separate opacity knobs for each one?

**Comment by peacechen** [comment]
I'll merge this as-is.  If someone else wants separate opacity controls, it will be another PR.

**Pull request merged**
