### PR TITLE
set selectTextStyle propType to Text.propTypes.style

### PR DESCRIPTION
**Pull request by mienaikoe**
https://github.com/peacechen/react-native-modal-selector/issues/25

### CODE REVIEW

**Comment by mienaikoe** [comment]
Sure, Maybe this could be done under a different issue ticket tho.

**Comment by peacechen** [comment]
If it's not too much trouble, would you mind updating all the style props with `PropTypes.oneOfType` ?  I won't be able to get to it right now and it'll likely fall through the cracks with my bad memory :D

**Comment by mikaello** [comment]
I have tried to investigate prop types for arrays in style-properties, but it seems that this is somehow included in `Text.propTypes.style` (and other prop types for styles from RN). There is no warning in debug-mode when using arrays without explicit specifying it.

In `Text` from RN all [properties](https://github.com/facebook/react-native/blob/master/Libraries/Text/TextStylePropTypes.js) goes trough [a function](https://github.com/facebook/react-native/blob/master/Libraries/StyleSheet/StyleSheetPropType.js) which [flattens any array](https://github.com/facebook/react-native/blob/master/Libraries/StyleSheet/flattenStyle.js) present. So as far as I can see `Text.propTypes.style` accepts both objects and arrays with objects. `ViewPropTypes` [uses the same function](https://github.com/facebook/react-native/blob/master/Libraries/Components/View/ViewPropTypes.js#L32).

Other well maintained react-native modules seem to just use `Text.propTypes.style`, and not `PropTypes.oneOfType` to include array, e.g. [react-native-elements Search inputStyle](https://github.com/react-native-training/react-native-elements/blob/master/src/input/Search.js#L130).

So I think this PR is good to go, and no further editing is necessary.

**Comment by peacechen** [comment]
Thanks @mikaello for clarifying the style proptypes behavior.  Wasn't aware that arrays are automatically flattened first.

**Pull request merged**
