### PR TITLE
Addition of multipicker feature

### PR DESCRIPTION
**Pull request by allroundexperts**
Addition of multiple select option.

### CODE REVIEW

**Comment by peacechen** [comment]
Thanks for the PR @allroundexperts 
I'll try it out and provide additional feedback soon.

On initial review, I noticed that you removed the modalOpenerHitSlop default prop as well as removed passing on hitSlop.  Was there a reason for removing those?

**Comment by flavinger** [comment]
Hi! Any updates about this? I am also interested in having a multi-select feature.

**Comment by allroundexperts** [comment]
> Hi! Any updates about this? I am also interested in having a multi-select feature.

You can use this repository:
https://github.com/allroundexperts/react-native-modal-multiselector

**Comment by allroundexperts** [comment]
> Thanks for the PR @allroundexperts
> I'll try it out and provide additional feedback soon.
> 
> On initial review, I noticed that you removed the modalOpenerHitSlop default prop as well as removed passing on hitSlop. Was there a reason for removing those?

Sorry for the late reply. I did not receive any notifications for this.
I'll review the changes and pull again.

**Comment by flavinger** [comment]
> > Hi! Any updates about this? I am also interested in having a multi-select feature.
> 
> You can use this repository:
> https://github.com/allroundexperts/react-native-modal-multiselector

Since my project already has a dependency on this repo, I'd prefer the change get in here.

**Comment by allroundexperts** [comment]
> Since my p

Is it something very urgent? 

I've been pretty busy lately.

**Comment by flavinger** [comment]
> > Since my p
> 
> Is it something very urgent?
> 
> I've been pretty busy lately.

I'm working on a feature that requires a multi-select picker. Since my project already has a dependency on this modal selector, ideally I'd like to see if the multipicker addition can get in this week. Would that be possible? Let me know if there is anything I can do to contribute.

**Comment by allroundexperts** [comment]
> > > Since my p
> > 
> > 
> > Is it something very urgent?
> > I've been pretty busy lately.
> 
> I'm working on a feature that requires a multi-select picker. Since my project already has a dependency on this modal selector, ideally I'd like to see if the multipicker addition can get in this week. Would that be possible? Let me know if there is anything I can do to contribute.

I'll try my best to do this within this week.

**Comment by peacechen** [comment]
@flavinger 
This is a community supported open source project.  We contribute as we have time and with features that we use.  It would be great if you would help out with this PR.  There are conflicts due to other more recent changes.  Also `modalOpenerHitSlop` and `hitSlop` props were removed which need to be reverted.

Since you may not have permission to modify @allroundexperts repo, you could clone the code from his PR, fix the issues and submit a new PR.

**Comment by peacechen** [comment]
Sibtain Ali - I noticed that you pushed a commit to this PR.  Please update the formatting to match the eslint config and the rest of the code.  A number of diffs are spacing and cosmetic changes which make it difficult to see the functional changes.

`modalOpenerHitSlop` still hasn't been restored. That prop is being used by apps and needs to remain.

**Pull request closed without merging**
