### PR TITLE
Add hitSlop prop

### PR DESCRIPTION
**Pull request by MattyK14**

### CODE REVIEW

**Comment by peacechen** [comment]
Thanks for the PR.  Something to consider is that there is another TouchableOpacity:
https://github.com/peacechen/react-native-modal-selector/blob/5820e30b5d58112f361090192d84e7c78bdbc3f3/index.js#L160

and a TouchableWithoutFeedback:
https://github.com/peacechen/react-native-modal-selector/blob/5820e30b5d58112f361090192d84e7c78bdbc3f3/index.js#L187

Should the same `hitSlop` be passed to those as well?  Or should each have its own unique hitSlop?

**Comment by MattyK14** [comment]
Passing it to the options would lead to overlapping touch areas. Not sure I see what the `TouchableWithoutFeedback` is for.

**Comment by peacechen** [comment]
Since there are other Touchables, please rename the prop to something more descriptive such as `openButtonHitSlop`.  In addition to describing which component it applies to, it allows for the addition of a future hitSlop prop on the other Touchables if that's desired.

**Comment by peacechen** [comment]
Thanks @MattyK14 👍

**Pull request merged**
